name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Default Scheme
        id: set_scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          default_scheme=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.read)['project']['targets'][0]")
          echo "default_scheme=$default_scheme" >> $GITHUB_ENV
          echo "Using default scheme: $default_scheme"

      - name: Build and Analyze
        env:
          scheme: ${{ env.default_scheme }}
        run: |
          scheme="$scheme"
          # Determine if workspace or project exists
          if ls -A | grep -i '\.xcworkspace$' &> /dev/null; then
            filetype_parameter="workspace"
            file_to_build=$(ls -A | grep -i '\.xcworkspace$')
          else
            filetype_parameter="project"
            file_to_build=$(ls -A | grep -i '\.xcodeproj$')
          fi
          file_to_build=$(echo "$file_to_build" | awk '{$1=$1;print}')  # trim whitespace
          echo "Building scheme: $scheme"
          echo "Building file: $file_to_build as $filetype_parameter"
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
          exit ${PIPESTATUS[0]}
